version: '3.1'

services:
  frontend: 
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile

    networks:
      - proxy
    
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      - ./shared:/app/shared

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile

    networks:
      - proxy
      - backend

    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
      - ./shared:/app/shared

  web: 
    container_name: web
    image: nginx:alpine

    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - proxy

  db:
    container_name: db
    image: postgres:alpine

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clay
    
    networks:
      - backend
    
    volumes:
      - ./db/data:/var/lib/postgresql/data

networks:
  proxy:
    driver: bridge
  backend:
    internal: true
